-- SQL file to add additional Bible Trivia Questions
-- Target: 300 easy, 150 moderate, 100 hard questions
-- Current: 100 easy, 100 moderate, 100 hard (from JS file)
-- Need to add: 200 easy, 50 moderate, 0 hard

-- This file contains INSERT statements for additional questions
-- Run this after migrating the initial 300 questions from the JS file

-- ========== ADDITIONAL EASY QUESTIONS (101-300) ==========
-- Add 200 more easy questions below

-- Example format for easy questions:
/*
INSERT INTO bible_trivia_questions (
    question, 
    option_1, 
    option_2, 
    option_3, 
    option_4, 
    correct_answer_index, 
    difficulty, 
    bible_book, 
    bible_chapter, 
    bible_verse,
    created_at
) VALUES (
    'Question text here?',
    'Option 1',
    'Option 2',
    'Option 3',
    'Option 4',
    0,  -- 0 = first option, 1 = second, 2 = third, 3 = fourth
    'easy',
    'Book Name',
    ChapterNumber,
    VerseNumber,
    NOW()
);
*/

-- Sample Easy Questions (Add 200 more following this format):

INSERT INTO bible_trivia_questions (question, option_1, option_2, option_3, option_4, correct_answer_index, difficulty, bible_book, bible_chapter, bible_verse, created_at) VALUES
('Who was the mother of Jesus?', 'Mary', 'Elizabeth', 'Sarah', 'Ruth', 0, 'easy', 'Matthew', 1, 18, NOW()),
('What is the first book of the Bible?', 'Exodus', 'Genesis', 'Leviticus', 'Numbers', 1, 'easy', 'Genesis', 1, 1, NOW()),
('Who wrote most of the Psalms?', 'Solomon', 'David', 'Moses', 'Isaiah', 1, 'easy', 'Psalms', 1, 1, NOW()),
('What is the last book of the Bible?', 'Jude', 'Revelation', '3 John', '2 Peter', 1, 'easy', 'Revelation', 22, 21, NOW()),
('How many books are in the New Testament?', '25', '26', '27', '28', 2, 'easy', NULL, NULL, NULL, NOW()),
('Who baptized Jesus?', 'Peter', 'John the Baptist', 'Paul', 'Andrew', 1, 'easy', 'Matthew', 3, 13, NOW()),
('What was the name of Jesus'' mother?', 'Mary', 'Martha', 'Elizabeth', 'Anna', 0, 'easy', 'Luke', 1, 27, NOW()),
('Who was the first king of Israel?', 'David', 'Saul', 'Solomon', 'Samuel', 1, 'easy', '1 Samuel', 10, 1, NOW()),
('What did Jesus turn water into at the wedding?', 'Wine', 'Milk', 'Juice', 'Honey', 0, 'easy', 'John', 2, 9, NOW()),
('Who denied Jesus three times?', 'Judas', 'Peter', 'Thomas', 'John', 1, 'easy', 'Matthew', 26, 75, NOW()),
('What is the shortest verse in the Bible?', 'Jesus wept', 'God is love', 'Pray always', 'Love one another', 0, 'easy', 'John', 11, 35, NOW()),
('Who was thrown into a fiery furnace?', 'Daniel', 'Shadrach, Meshach, and Abednego', 'Moses', 'Elijah', 1, 'easy', 'Daniel', 3, 23, NOW()),
('What did Jesus ride into Jerusalem?', 'A horse', 'A donkey', 'A camel', 'He walked', 1, 'easy', 'Matthew', 21, 7, NOW()),
('Who built the first temple in Jerusalem?', 'David', 'Solomon', 'Saul', 'Hezekiah', 1, 'easy', '1 Kings', 6, 1, NOW()),
('What is the longest book in the Bible?', 'Genesis', 'Psalms', 'Isaiah', 'Jeremiah', 1, 'easy', 'Psalms', NULL, NULL, NOW()),
('Who was the wisest king?', 'David', 'Solomon', 'Saul', 'Hezekiah', 1, 'easy', '1 Kings', 3, 12, NOW()),
('What did God create on the first day?', 'Animals', 'Light', 'Plants', 'People', 1, 'easy', 'Genesis', 1, 3, NOW()),
('Who was the father of Isaac?', 'Noah', 'Abraham', 'Jacob', 'Moses', 1, 'easy', 'Genesis', 21, 3, NOW()),
('What is the name of the sea Jesus walked on?', 'Red Sea', 'Dead Sea', 'Sea of Galilee', 'Mediterranean Sea', 2, 'easy', 'Matthew', 14, 25, NOW()),
('Who was the first disciple Jesus called?', 'Peter', 'Andrew', 'John', 'James', 1, 'easy', 'Matthew', 4, 18, NOW()),
('What did the wise men bring to Jesus?', 'Gold, frankincense, and myrrh', 'Silver and gold', 'Food and clothes', 'Toys and books', 0, 'easy', 'Matthew', 2, 11, NOW()),
('Who was the strongest man in the Bible?', 'Goliath', 'Samson', 'David', 'Saul', 1, 'easy', 'Judges', 16, 17, NOW()),
('What happened to Samson''s strength?', 'It left when his hair was cut', 'It left when he got old', 'It left when he sinned', 'It never left', 0, 'easy', 'Judges', 16, 19, NOW()),
('Who was swallowed by a big fish?', 'Moses', 'Jonah', 'Daniel', 'Noah', 1, 'easy', 'Jonah', 1, 17, NOW()),
('What is the name of the garden where Jesus prayed before his death?', 'Garden of Eden', 'Garden of Gethsemane', 'Garden of Paradise', 'Garden of Heaven', 1, 'easy', 'Matthew', 26, 36, NOW()),
('Who was the first woman?', 'Sarah', 'Eve', 'Ruth', 'Mary', 1, 'easy', 'Genesis', 2, 22, NOW()),
('What did God use to create Eve?', 'Clay', 'Dust', 'A rib from Adam', 'Water', 2, 'easy', 'Genesis', 2, 22, NOW()),
('Who was the first murderer?', 'Cain', 'Abel', 'Lamech', 'Noah', 0, 'easy', 'Genesis', 4, 8, NOW()),
('What did Cain do for a living?', 'He was a farmer', 'He was a shepherd', 'He was a builder', 'He was a fisherman', 0, 'easy', 'Genesis', 4, 2, NOW()),
('How many people were on Noah''s ark?', '4', '6', '8', '10', 2, 'easy', 'Genesis', 7, 13, NOW()),
('What color was the robe Joseph''s father gave him?', 'Red', 'Blue', 'Many colors', 'White', 2, 'easy', 'Genesis', 37, 3, NOW()),
('Who interpreted dreams in Egypt?', 'Moses', 'Joseph', 'Daniel', 'Samuel', 1, 'easy', 'Genesis', 41, 15, NOW()),
('What did Moses'' mother put him in?', 'A basket', 'A box', 'A boat', 'A bag', 0, 'easy', 'Exodus', 2, 3, NOW()),
('Who found Moses in the river?', 'His mother', 'Pharaoh''s daughter', 'His sister', 'A shepherd', 1, 'easy', 'Exodus', 2, 5, NOW()),
('What did God speak to Moses from?', 'A cloud', 'A burning bush', 'A mountain', 'The sky', 1, 'easy', 'Exodus', 3, 2, NOW()),
('What was the first plague?', 'Frogs', 'Water to blood', 'Flies', 'Locusts', 1, 'easy', 'Exodus', 7, 20, NOW()),
('What did the Israelites eat in the desert?', 'Bread and meat', 'Manna and quail', 'Fish and fruit', 'Rice and vegetables', 1, 'easy', 'Exodus', 16, 13, NOW()),
('Who was Moses'' brother?', 'Aaron', 'Joshua', 'Caleb', 'Miriam', 0, 'easy', 'Exodus', 4, 14, NOW()),
('What did God give the Israelites on Mount Sinai?', 'Food', 'Water', 'The Ten Commandments', 'Weapons', 2, 'easy', 'Exodus', 20, 1, NOW()),
('Who led the Israelites after Moses?', 'Aaron', 'Joshua', 'Caleb', 'Samuel', 1, 'easy', 'Joshua', 1, 1, NOW()),
('What city did the walls fall down?', 'Jerusalem', 'Jericho', 'Bethlehem', 'Nazareth', 1, 'easy', 'Joshua', 6, 20, NOW()),
('Who was the first judge?', 'Gideon', 'Samson', 'Deborah', 'Othniel', 3, 'easy', 'Judges', 3, 9, NOW()),
('Who was a judge and a prophetess?', 'Miriam', 'Deborah', 'Ruth', 'Esther', 1, 'easy', 'Judges', 4, 4, NOW()),
('Who was Ruth''s mother-in-law?', 'Naomi', 'Sarah', 'Rebekah', 'Leah', 0, 'easy', 'Ruth', 1, 4, NOW()),
('Who was the great-grandfather of David?', 'Jesse', 'Boaz', 'Obed', 'Salmon', 1, 'easy', 'Ruth', 4, 21, NOW()),
('Who anointed David as king?', 'Samuel', 'Saul', 'Nathan', 'Gad', 0, 'easy', '1 Samuel', 16, 13, NOW()),
('Who was David''s best friend?', 'Jonathan', 'Saul', 'Goliath', 'Samuel', 0, 'easy', '1 Samuel', 18, 1, NOW()),
('How many psalms are in the Book of Psalms?', '100', '120', '150', '200', 2, 'easy', 'Psalms', NULL, NULL, NOW()),
('Who wrote the Book of Proverbs?', 'David', 'Solomon', 'Isaiah', 'Jeremiah', 1, 'easy', 'Proverbs', 1, 1, NOW()),
('What is the theme of Ecclesiastes?', 'Love', 'Wisdom', 'Everything is meaningless', 'Hope', 2, 'easy', 'Ecclesiastes', 1, 2, NOW()),
('Who was thrown into a lions'' den?', 'Daniel', 'Shadrach', 'Meshach', 'Abednego', 0, 'easy', 'Daniel', 6, 16, NOW()),
('How many days was Daniel in the lions'' den?', 'One night', 'Three days', 'Seven days', 'Forty days', 0, 'easy', 'Daniel', 6, 19, NOW()),
('Who was the prophet who was taken to heaven in a chariot?', 'Elisha', 'Elijah', 'Isaiah', 'Jeremiah', 1, 'easy', '2 Kings', 2, 11, NOW()),
('What prophet was swallowed by a fish?', 'Jonah', 'Daniel', 'Isaiah', 'Jeremiah', 0, 'easy', 'Jonah', 1, 17, NOW()),
('Where was Jesus born?', 'Nazareth', 'Bethlehem', 'Jerusalem', 'Jericho', 1, 'easy', 'Luke', 2, 4, NOW()),
('Who announced Jesus'' birth to the shepherds?', 'An angel', 'A star', 'A wise man', 'A prophet', 0, 'easy', 'Luke', 2, 9, NOW()),
('How old was Jesus when he was found in the temple?', '10', '12', '15', '18', 1, 'easy', 'Luke', 2, 42, NOW()),
('Who was Jesus'' earthly father?', 'Joseph', 'David', 'Abraham', 'Jacob', 0, 'easy', 'Matthew', 1, 16, NOW()),
('What was Jesus'' job before he started preaching?', 'Fisherman', 'Carpenter', 'Shepherd', 'Farmer', 1, 'easy', 'Mark', 6, 3, NOW()),
('Who was the first person to see Jesus after he rose from the dead?', 'Peter', 'Mary Magdalene', 'John', 'Thomas', 1, 'easy', 'John', 20, 14, NOW()),
('How many days was Jesus in the tomb?', '1 day', '2 days', '3 days', '4 days', 2, 'easy', 'Matthew', 12, 40, NOW()),
('Who betrayed Jesus?', 'Peter', 'Judas', 'Thomas', 'John', 1, 'easy', 'Matthew', 26, 14, NOW()),
('What did Jesus do at the Last Supper?', 'Washed feet', 'Gave a sermon', 'Performed a miracle', 'Broke bread and shared wine', 3, 'easy', 'Matthew', 26, 26, NOW()),
('Who wrote most of the New Testament letters?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', NULL, NULL, NULL, NOW()),
('What is the first book of the New Testament?', 'Mark', 'Luke', 'John', 'Matthew', 3, 'easy', 'Matthew', 1, 1, NOW()),
('How many Gospels are in the New Testament?', '3', '4', '5', '6', 1, 'easy', NULL, NULL, NULL, NOW()),
('What does "Gospel" mean?', 'Story', 'Good news', 'History', 'Letter', 1, 'easy', NULL, NULL, NULL, NOW()),
('Who wrote the Book of Acts?', 'Luke', 'Paul', 'Peter', 'John', 0, 'easy', 'Acts', 1, 1, NOW()),
('What happened on the Day of Pentecost?', 'Jesus was born', 'The Holy Spirit came', 'Jesus died', 'Jesus rose', 1, 'easy', 'Acts', 2, 1, NOW()),
('Who was the first Christian martyr?', 'Peter', 'Paul', 'Stephen', 'James', 2, 'easy', 'Acts', 7, 59, NOW()),
('Who was converted on the road to Damascus?', 'Peter', 'Paul', 'Stephen', 'Barnabas', 1, 'easy', 'Acts', 9, 3, NOW()),
('What was Paul''s name before he became a Christian?', 'Peter', 'Saul', 'Simon', 'John', 1, 'easy', 'Acts', 9, 1, NOW()),
('How many books did Paul write?', '10', '13', '15', '20', 1, 'easy', NULL, NULL, NULL, NOW()),
('What is the shortest book in the New Testament?', 'Philemon', '2 John', '3 John', 'Jude', 2, 'easy', '3 John', NULL, NULL, NOW()),
('What is the last book of the Bible?', 'Jude', 'Revelation', '3 John', '2 Peter', 1, 'easy', 'Revelation', 22, 21, NOW()),
('Who wrote the Book of Revelation?', 'Paul', 'Peter', 'John', 'James', 2, 'easy', 'Revelation', 1, 1, NOW()),
('What are the four Gospels?', 'Matthew, Mark, Luke, John', 'Matthew, Mark, Paul, John', 'Luke, John, Acts, Romans', 'Matthew, Luke, John, Revelation', 0, 'easy', NULL, NULL, NULL, NOW()),
('What is the longest Gospel?', 'Matthew', 'Mark', 'Luke', 'John', 2, 'easy', 'Luke', NULL, NULL, NOW()),
('What is the shortest Gospel?', 'Matthew', 'Mark', 'Luke', 'John', 1, 'easy', 'Mark', NULL, NULL, NOW()),
('Who was known as "Doubting Thomas"?', 'Thomas the disciple', 'Thomas the apostle', 'Thomas the tax collector', 'Thomas the fisherman', 0, 'easy', 'John', 20, 24, NOW()),
('What did Thomas want to see before believing?', 'Jesus'' face', 'Jesus'' hands and side', 'Jesus'' feet', 'A miracle', 1, 'easy', 'John', 20, 25, NOW()),
('Who was the tax collector that became a disciple?', 'Matthew', 'Mark', 'Luke', 'John', 0, 'easy', 'Matthew', 9, 9, NOW()),
('What did Zacchaeus do to see Jesus?', 'Climbed a tree', 'Pushed through the crowd', 'Asked someone', 'Stood on a box', 0, 'easy', 'Luke', 19, 4, NOW()),
('How many times did Peter deny Jesus?', '1', '2', '3', '4', 2, 'easy', 'Matthew', 26, 75, NOW()),
('What did Jesus say to Peter after he denied him?', 'I forgive you', 'Follow me', 'Feed my sheep', 'Go and sin no more', 2, 'easy', 'John', 21, 17, NOW()),
('Who was the disciple Jesus loved?', 'Peter', 'John', 'James', 'Andrew', 1, 'easy', 'John', 13, 23, NOW()),
('What did Jesus do to show he was a servant?', 'Prayed', 'Washed the disciples'' feet', 'Preached', 'Performed a miracle', 1, 'easy', 'John', 13, 5, NOW()),
('What is the Golden Rule?', 'Love God', 'Do to others as you want them to do to you', 'Honor your parents', 'Do not steal', 1, 'easy', 'Matthew', 7, 12, NOW()),
('What is the greatest commandment?', 'Love your neighbor', 'Love God with all your heart', 'Do not kill', 'Keep the Sabbath', 1, 'easy', 'Matthew', 22, 37, NOW()),
('What is the second greatest commandment?', 'Love God', 'Love your neighbor as yourself', 'Honor your parents', 'Do not steal', 1, 'easy', 'Matthew', 22, 39, NOW()),
('What did Jesus say about the poor?', 'They are blessed', 'They are cursed', 'They are lazy', 'They are forgotten', 0, 'easy', 'Matthew', 5, 3, NOW()),
('What did Jesus say about children?', 'Let them come to me', 'Send them away', 'They are trouble', 'They are not important', 0, 'easy', 'Matthew', 19, 14, NOW()),
('What is a parable?', 'A story with a meaning', 'A prayer', 'A song', 'A law', 0, 'easy', NULL, NULL, NULL, NOW()),
('How many parables did Jesus tell?', 'About 20', 'About 30', 'About 40', 'About 50', 2, 'easy', NULL, NULL, NULL, NOW()),
('What is the Parable of the Good Samaritan about?', 'Helping others', 'Praying', 'Giving money', 'Going to church', 0, 'easy', 'Luke', 10, 30, NOW()),
('What is the Parable of the Prodigal Son about?', 'Forgiveness', 'Money', 'Work', 'Travel', 0, 'easy', 'Luke', 15, 11, NOW()),
('What is the Parable of the Lost Sheep about?', 'Finding something', 'God''s love for us', 'Sheep', 'Being lost', 1, 'easy', 'Luke', 15, 4, NOW()),
('What did Jesus say he was?', 'A teacher', 'The way, the truth, and the life', 'A prophet', 'A king', 1, 'easy', 'John', 14, 6, NOW()),
('What did Jesus call himself?', 'The Good Shepherd', 'The Light of the World', 'The Bread of Life', 'All of the above', 3, 'easy', NULL, NULL, NULL, NOW()),
('What miracle did Jesus perform at a wedding?', 'Healed someone', 'Turned water into wine', 'Fed many people', 'Walked on water', 1, 'easy', 'John', 2, 9, NOW()),
('How many people did Jesus feed with 5 loaves and 2 fish?', '1000', '3000', '5000', '10000', 2, 'easy', 'Matthew', 14, 21, NOW()),
('How many times did Jesus feed a large crowd?', '1', '2', '3', '4', 1, 'easy', NULL, NULL, NULL, NOW()),
('Who walked on water with Jesus?', 'Peter', 'John', 'James', 'Andrew', 0, 'easy', 'Matthew', 14, 29, NOW()),
('How many times did Jesus raise someone from the dead?', '1', '2', '3', '4', 2, 'easy', NULL, NULL, NULL, NOW()),
('Who did Jesus raise from the dead?', 'Lazarus, Jairus'' daughter, and a widow''s son', 'Only Lazarus', 'Only Jairus'' daughter', 'Only a widow''s son', 0, 'easy', NULL, NULL, NULL, NOW()),
('What did Jesus do when he entered Jerusalem?', 'He rode a donkey', 'He walked', 'He rode a horse', 'He was carried', 0, 'easy', 'Matthew', 21, 7, NOW()),
('What did people wave when Jesus entered Jerusalem?', 'Flags', 'Palm branches', 'Handkerchiefs', 'Swords', 1, 'easy', 'John', 12, 13, NOW()),
('What did people shout when Jesus entered Jerusalem?', 'Hosanna', 'Hallelujah', 'Amen', 'Praise God', 0, 'easy', 'Matthew', 21, 9, NOW()),
('What did Jesus do in the temple?', 'Prayed', 'Taught', 'Drove out the money changers', 'Healed people', 2, 'easy', 'Matthew', 21, 12, NOW()),
('What did Jesus say about the temple?', 'It is beautiful', 'It will be destroyed', 'It is holy', 'It is mine', 1, 'easy', 'Matthew', 24, 2, NOW()),
('Who washed Jesus'' feet with perfume?', 'Mary Magdalene', 'Mary the sister of Lazarus', 'A sinful woman', 'All of the above', 3, 'easy', 'John', 12, 3, NOW()),
('What did Jesus do at the Last Supper?', 'Ate with his disciples', 'Washed their feet', 'Gave them bread and wine', 'All of the above', 3, 'easy', 'Matthew', 26, 26, NOW()),
('What did Jesus say the bread represented?', 'His body', 'His blood', 'His spirit', 'His love', 0, 'easy', 'Matthew', 26, 26, NOW()),
('What did Jesus say the wine represented?', 'His body', 'His blood', 'His spirit', 'His love', 1, 'easy', 'Matthew', 26, 28, NOW()),
('Where did Jesus pray before he was arrested?', 'Garden of Eden', 'Garden of Gethsemane', 'Mount of Olives', 'Temple', 1, 'easy', 'Matthew', 26, 36, NOW()),
('Who arrested Jesus?', 'Roman soldiers', 'Jewish leaders', 'Both', 'Neither', 2, 'easy', 'Matthew', 26, 47, NOW()),
('Who was the high priest who questioned Jesus?', 'Annas', 'Caiaphas', 'Pilate', 'Herod', 1, 'easy', 'Matthew', 26, 57, NOW()),
('Who was the Roman governor who sentenced Jesus?', 'Herod', 'Pilate', 'Caiaphas', 'Annas', 1, 'easy', 'Matthew', 27, 2, NOW()),
('What did the crowd choose to release instead of Jesus?', 'A thief', 'Barabbas', 'A murderer', 'All of the above', 3, 'easy', 'Matthew', 27, 21, NOW()),
('What did the soldiers put on Jesus'' head?', 'A crown', 'A crown of thorns', 'A hat', 'Nothing', 1, 'easy', 'Matthew', 27, 29, NOW()),
('Where was Jesus crucified?', 'Golgotha', 'Calvary', 'The Place of the Skull', 'All of the above', 3, 'easy', 'Matthew', 27, 33, NOW()),
('What did the sign above Jesus say?', 'King of the Jews', 'This is Jesus', 'Savior of the World', 'Son of God', 0, 'easy', 'Matthew', 27, 37, NOW()),
('What did Jesus say on the cross?', '"Father, forgive them"', '"It is finished"', '"Into your hands I commit my spirit"', 'All of the above', 3, 'easy', 'Luke', 23, 34, NOW()),
('Who buried Jesus?', 'Joseph of Arimathea', 'Nicodemus', 'Both', 'Neither', 2, 'easy', 'John', 19, 38, NOW()),
('What day did Jesus rise from the dead?', 'Friday', 'Saturday', 'Sunday', 'Monday', 2, 'easy', 'Matthew', 28, 1, NOW()),
('Who was the first to see the empty tomb?', 'Peter', 'Mary Magdalene', 'John', 'The guards', 1, 'easy', 'John', 20, 1, NOW()),
('How many times did Jesus appear to his disciples after rising?', '5', '10', 'More than 10', 'Less than 5', 2, 'easy', NULL, NULL, NULL, NOW()),
('Where did Jesus ascend to heaven?', 'Mount of Olives', 'Mount Sinai', 'Mount Tabor', 'Mount Zion', 0, 'easy', 'Acts', 1, 9, NOW()),
('How many days after rising did Jesus ascend?', '30', '40', '50', '60', 1, 'easy', 'Acts', 1, 3, NOW()),
('What happened on the Day of Pentecost?', 'Jesus was born', 'The Holy Spirit came', 'Jesus died', 'Jesus rose', 1, 'easy', 'Acts', 2, 1, NOW()),
('How many people were added to the church on Pentecost?', 'About 1000', 'About 2000', 'About 3000', 'About 5000', 2, 'easy', 'Acts', 2, 41, NOW()),
('Who was the first person to preach after Pentecost?', 'Peter', 'Paul', 'John', 'James', 0, 'easy', 'Acts', 2, 14, NOW()),
('What happened to Ananias and Sapphira?', 'They were blessed', 'They died for lying', 'They were healed', 'They became leaders', 1, 'easy', 'Acts', 5, 5, NOW()),
('Who was the first Christian martyr?', 'Peter', 'Paul', 'Stephen', 'James', 2, 'easy', 'Acts', 7, 59, NOW()),
('Who was converted on the road to Damascus?', 'Peter', 'Paul', 'Stephen', 'Barnabas', 1, 'easy', 'Acts', 9, 3, NOW()),
('What was Paul''s job?', 'Fisherman', 'Tentmaker', 'Carpenter', 'Farmer', 1, 'easy', 'Acts', 18, 3, NOW()),
('How many missionary journeys did Paul take?', '1', '2', '3', '4', 2, 'easy', NULL, NULL, NULL, NOW()),
('Who wrote the Book of Romans?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', 'Romans', 1, 1, NOW()),
('What is the theme of 1 Corinthians 13?', 'Love', 'Faith', 'Hope', 'Joy', 0, 'easy', '1 Corinthians', 13, 1, NOW()),
('What is the fruit of the Spirit?', 'Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control', 'Just love', 'Just joy', 'Just peace', 0, 'easy', 'Galatians', 5, 22, NOW()),
('Who wrote the Book of Ephesians?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', 'Ephesians', 1, 1, NOW()),
('What is the armor of God?', 'Belt of truth, breastplate of righteousness, shoes of peace, shield of faith, helmet of salvation, sword of the Spirit', 'Just a shield', 'Just a sword', 'Just a helmet', 0, 'easy', 'Ephesians', 6, 13, NOW()),
('Who wrote the Book of Philippians?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', 'Philippians', 1, 1, NOW()),
('What is the theme of Philippians?', 'Joy', 'Love', 'Peace', 'Hope', 0, 'easy', 'Philippians', 4, 4, NOW()),
('Who wrote the Book of Colossians?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', 'Colossians', 1, 1, NOW()),
('Who wrote 1 and 2 Thessalonians?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', '1 Thessalonians', 1, 1, NOW()),
('Who wrote 1 and 2 Timothy?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', '1 Timothy', 1, 1, NOW()),
('Who wrote Titus?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', 'Titus', 1, 1, NOW()),
('Who wrote Philemon?', 'Peter', 'Paul', 'John', 'James', 1, 'easy', 'Philemon', 1, 1, NOW()),
('Who wrote the Book of Hebrews?', 'Unknown (possibly Paul)', 'Peter', 'John', 'James', 0, 'easy', 'Hebrews', 1, 1, NOW()),
('Who wrote the Book of James?', 'James the brother of Jesus', 'James the son of Zebedee', 'James the son of Alphaeus', 'All of the above', 0, 'easy', 'James', 1, 1, NOW()),
('Who wrote 1 and 2 Peter?', 'Peter', 'Paul', 'John', 'James', 0, 'easy', '1 Peter', 1, 1, NOW()),
('Who wrote 1, 2, and 3 John?', 'John the apostle', 'John the Baptist', 'John Mark', 'Another John', 0, 'easy', '1 John', 1, 1, NOW()),
('Who wrote the Book of Jude?', 'Jude the brother of Jesus', 'Judas Iscariot', 'Jude the apostle', 'Another Jude', 0, 'easy', 'Jude', 1, 1, NOW()),
('Who wrote the Book of Revelation?', 'John the apostle', 'John the Baptist', 'John Mark', 'Another John', 0, 'easy', 'Revelation', 1, 1, NOW()),
('What is the Book of Revelation about?', 'The end times', 'The future', 'Jesus'' return', 'All of the above', 3, 'easy', 'Revelation', NULL, NULL, NOW()),
('What is the New Jerusalem?', 'A city', 'Heaven', 'The new earth', 'All of the above', 3, 'easy', 'Revelation', 21, 2, NOW()),
('What is the tree of life?', 'A tree in the garden', 'A tree in heaven', 'A symbol of eternal life', 'All of the above', 3, 'easy', 'Revelation', 22, 2, NOW()),
('What did God create on the second day?', 'Land', 'Sky', 'Plants', 'Animals', 1, 'easy', 'Genesis', 1, 8, NOW()),
('What did God create on the third day?', 'Sun and moon', 'Land and plants', 'Birds and fish', 'Animals and people', 1, 'easy', 'Genesis', 1, 13, NOW()),
('What did God create on the fourth day?', 'Sun, moon, and stars', 'Birds and fish', 'Animals', 'People', 0, 'easy', 'Genesis', 1, 19, NOW()),
('What did God create on the fifth day?', 'Animals', 'Birds and fish', 'People', 'Plants', 1, 'easy', 'Genesis', 1, 23, NOW()),
('What did God create on the sixth day?', 'Animals and people', 'Just animals', 'Just people', 'Nothing', 0, 'easy', 'Genesis', 1, 31, NOW()),
('What did God do on the seventh day?', 'Created more things', 'Rested', 'Worked', 'Played', 1, 'easy', 'Genesis', 2, 2, NOW()),
('What was the name of Adam and Eve''s first son?', 'Abel', 'Cain', 'Seth', 'Noah', 1, 'easy', 'Genesis', 4, 1, NOW()),
('What was the name of Adam and Eve''s second son?', 'Cain', 'Abel', 'Seth', 'Noah', 1, 'easy', 'Genesis', 4, 2, NOW()),
('What was the name of Adam and Eve''s third son?', 'Cain', 'Abel', 'Seth', 'Noah', 2, 'easy', 'Genesis', 4, 25, NOW()),
('How old was Noah when the flood came?', '400 years old', '500 years old', '600 years old', '700 years old', 2, 'easy', 'Genesis', 7, 6, NOW()),
('How long did it rain during the flood?', '30 days', '40 days', '50 days', '60 days', 1, 'easy', 'Genesis', 7, 12, NOW()),
('What bird did Noah send out first?', 'A dove', 'A raven', 'A sparrow', 'An eagle', 1, 'easy', 'Genesis', 8, 7, NOW()),
('What bird did Noah send out that didn''t come back?', 'A raven', 'A dove', 'A sparrow', 'An eagle', 1, 'easy', 'Genesis', 8, 12, NOW()),
('What was the name of Abraham''s wife?', 'Sarah', 'Rebekah', 'Rachel', 'Leah', 0, 'easy', 'Genesis', 11, 29, NOW()),
('What was the name of Isaac''s wife?', 'Sarah', 'Rebekah', 'Rachel', 'Leah', 1, 'easy', 'Genesis', 24, 67, NOW()),
('What were the names of Isaac''s twin sons?', 'Jacob and Esau', 'Joseph and Benjamin', 'Moses and Aaron', 'David and Jonathan', 0, 'easy', 'Genesis', 25, 26, NOW()),
('What did Esau sell to Jacob?', 'His birthright', 'His land', 'His animals', 'His house', 0, 'easy', 'Genesis', 25, 33, NOW()),
('What was Jacob''s name changed to?', 'Israel', 'Judah', 'Joseph', 'Benjamin', 0, 'easy', 'Genesis', 32, 28, NOW()),
('How many years did Jacob work for Rachel?', '7 years', '14 years', '21 years', '28 years', 1, 'easy', 'Genesis', 29, 20, NOW()),
('What was the name of Joseph''s father?', 'Isaac', 'Jacob', 'Abraham', 'Noah', 1, 'easy', 'Genesis', 37, 3, NOW()),
('What was Joseph''s special gift?', 'Interpreting dreams', 'Fighting', 'Building', 'Farming', 0, 'easy', 'Genesis', 40, 8, NOW()),
('Who was Joseph''s youngest brother?', 'Reuben', 'Benjamin', 'Judah', 'Levi', 1, 'easy', 'Genesis', 42, 13, NOW()),
('How many years of plenty did Joseph predict?', '5 years', '7 years', '10 years', '12 years', 1, 'easy', 'Genesis', 41, 29, NOW()),
('How many years of famine did Joseph predict?', '5 years', '7 years', '10 years', '12 years', 1, 'easy', 'Genesis', 41, 30, NOW()),
('What was the name of Moses'' sister?', 'Miriam', 'Zipporah', 'Jochebed', 'Shiphrah', 0, 'easy', 'Exodus', 2, 4, NOW()),
('What was the name of Moses'' brother?', 'Aaron', 'Joshua', 'Caleb', 'Eleazar', 0, 'easy', 'Exodus', 4, 14, NOW()),
('What was the name of Moses'' wife?', 'Miriam', 'Zipporah', 'Jochebed', 'Shiphrah', 1, 'easy', 'Exodus', 2, 21, NOW()),
('What was the first plague?', 'Frogs', 'Water to blood', 'Flies', 'Locusts', 1, 'easy', 'Exodus', 7, 20, NOW()),
('What was the second plague?', 'Frogs', 'Water to blood', 'Flies', 'Locusts', 0, 'easy', 'Exodus', 8, 2, NOW()),
('What was the third plague?', 'Gnats', 'Flies', 'Locusts', 'Hail', 0, 'easy', 'Exodus', 8, 16, NOW()),
('What was the fourth plague?', 'Flies', 'Locusts', 'Hail', 'Darkness', 0, 'easy', 'Exodus', 8, 21, NOW()),
('What was the fifth plague?', 'Death of livestock', 'Boils', 'Hail', 'Locusts', 0, 'easy', 'Exodus', 9, 3, NOW()),
('What was the sixth plague?', 'Boils', 'Hail', 'Locusts', 'Darkness', 0, 'easy', 'Exodus', 9, 9, NOW()),
('What was the seventh plague?', 'Hail', 'Locusts', 'Darkness', 'Death of firstborn', 0, 'easy', 'Exodus', 9, 18, NOW()),
('What was the eighth plague?', 'Locusts', 'Darkness', 'Death of firstborn', 'Frogs', 0, 'easy', 'Exodus', 10, 4, NOW()),
('What was the ninth plague?', 'Darkness', 'Death of firstborn', 'Frogs', 'Flies', 0, 'easy', 'Exodus', 10, 21, NOW()),
('What was the tenth plague?', 'Death of firstborn', 'Darkness', 'Locusts', 'Hail', 0, 'easy', 'Exodus', 12, 29, NOW()),
('What did the Israelites put on their doorposts?', 'Blood of a lamb', 'Paint', 'A sign', 'Nothing', 0, 'easy', 'Exodus', 12, 7, NOW()),
('What did God provide for food in the desert?', 'Bread and meat', 'Manna and quail', 'Fish and fruit', 'Rice and vegetables', 1, 'easy', 'Exodus', 16, 13, NOW()),
('What did God provide for water in the desert?', 'Water from a rock', 'Water from a well', 'Water from a river', 'Rain', 0, 'easy', 'Exodus', 17, 6, NOW()),
('Who helped Moses hold up his arms during battle?', 'Aaron and Hur', 'Joshua and Caleb', 'Miriam and Zipporah', 'Eleazar and Ithamar', 0, 'easy', 'Exodus', 17, 12, NOW()),
('What did God give Moses on Mount Sinai?', 'The Ten Commandments', 'A staff', 'A crown', 'A book', 0, 'easy', 'Exodus', 20, 1, NOW()),
('How many commandments are there?', '5', '10', '12', '15', 1, 'easy', 'Exodus', 20, 1, NOW()),
('What was the first commandment?', 'You shall have no other gods', 'Honor your father and mother', 'You shall not steal', 'You shall not kill', 0, 'easy', 'Exodus', 20, 3, NOW()),
('What was the second commandment?', 'You shall not make idols', 'You shall not take God''s name in vain', 'Remember the Sabbath', 'Honor your parents', 0, 'easy', 'Exodus', 20, 4, NOW()),
('What was the third commandment?', 'You shall not take God''s name in vain', 'Remember the Sabbath', 'Honor your parents', 'You shall not kill', 0, 'easy', 'Exodus', 20, 7, NOW()),
('What was the fourth commandment?', 'Remember the Sabbath', 'Honor your parents', 'You shall not kill', 'You shall not steal', 0, 'easy', 'Exodus', 20, 8, NOW()),
('What was the fifth commandment?', 'Honor your father and mother', 'You shall not kill', 'You shall not steal', 'You shall not lie', 0, 'easy', 'Exodus', 20, 12, NOW()),
('What was the sixth commandment?', 'You shall not kill', 'You shall not steal', 'You shall not lie', 'You shall not covet', 0, 'easy', 'Exodus', 20, 13, NOW()),
('What was the seventh commandment?', 'You shall not commit adultery', 'You shall not steal', 'You shall not lie', 'You shall not covet', 0, 'easy', 'Exodus', 20, 14, NOW()),
('What was the eighth commandment?', 'You shall not steal', 'You shall not lie', 'You shall not covet', 'You shall have no other gods', 0, 'easy', 'Exodus', 20, 15, NOW()),
('What was the ninth commandment?', 'You shall not give false testimony', 'You shall not covet', 'You shall have no other gods', 'Honor your parents', 0, 'easy', 'Exodus', 20, 16, NOW()),
('What was the tenth commandment?', 'You shall not covet', 'You shall have no other gods', 'Honor your parents', 'You shall not kill', 0, 'easy', 'Exodus', 20, 17, NOW()),
('What happened when Moses came down from the mountain?', 'He saw the golden calf', 'He saw the people worshiping', 'He broke the tablets', 'All of the above', 3, 'easy', 'Exodus', 32, 19, NOW()),
('Who made the golden calf?', 'Aaron', 'Moses', 'Joshua', 'Caleb', 0, 'easy', 'Exodus', 32, 4, NOW()),
('What did Moses do with the golden calf?', 'Burned it and ground it to powder', 'Kept it', 'Gave it away', 'Buried it', 0, 'easy', 'Exodus', 32, 20, NOW()),
('How many times did Moses go up Mount Sinai?', '1 time', '2 times', '3 times', '4 times', 1, 'easy', 'Exodus', 34, 4, NOW()),
('What was built in the desert for worship?', 'A temple', 'A tabernacle', 'An altar', 'A tower', 1, 'easy', 'Exodus', 25, 8, NOW()),
('Who was chosen to lead after Moses?', 'Aaron', 'Joshua', 'Caleb', 'Eleazar', 1, 'easy', 'Numbers', 27, 18, NOW()),
('How many spies gave a good report?', '2', '10', '12', '14', 0, 'easy', 'Numbers', 14, 6, NOW()),
('What were the names of the two good spies?', 'Joshua and Caleb', 'Joshua and Eleazar', 'Caleb and Phinehas', 'Joshua and Phinehas', 0, 'easy', 'Numbers', 14, 6, NOW()),
('What happened to the bad spies?', 'They died', 'They were sent away', 'They were punished', 'All of the above', 0, 'easy', 'Numbers', 14, 37, NOW()),
('How many years did the Israelites wander?', '30 years', '40 years', '50 years', '60 years', 1, 'easy', 'Numbers', 14, 33, NOW()),
('What happened when the Israelites looked at the bronze snake?', 'They were healed', 'They died', 'Nothing', 'They were blessed', 0, 'easy', 'Numbers', 21, 9, NOW()),
('Who was the first judge?', 'Othniel', 'Ehud', 'Shamgar', 'Deborah', 0, 'easy', 'Judges', 3, 9, NOW()),
('What did Deborah do?', 'Was a judge and prophetess', 'Led Israel to victory', 'Settled disputes', 'All of the above', 3, 'easy', 'Judges', 4, 4, NOW()),
('What did Gideon ask for as a sign?', 'A wet fleece and dry ground', 'A dry fleece and wet ground', 'Both', 'Neither', 2, 'easy', 'Judges', 6, 37, NOW()),
('How many men did Gideon have in his army?', '100', '200', '300', '400', 2, 'easy', 'Judges', 7, 7, NOW()),
('What did Gideon''s men use to fight?', 'Swords', 'Spears', 'Trumpets and torches', 'Bows and arrows', 2, 'easy', 'Judges', 7, 20, NOW()),
('What was Samson known for?', 'His strength', 'His wisdom', 'His wealth', 'His beauty', 0, 'easy', 'Judges', 16, 17, NOW()),
('What was the secret of Samson''s strength?', 'His hair', 'His muscles', 'His faith', 'His diet', 0, 'easy', 'Judges', 16, 17, NOW()),
('Who cut Samson''s hair?', 'Delilah', 'His mother', 'His father', 'A Philistine', 0, 'easy', 'Judges', 16, 19, NOW()),
('What happened to Samson''s eyes?', 'They were gouged out', 'He went blind', 'He closed them', 'Nothing', 0, 'easy', 'Judges', 16, 21, NOW()),
('How did Samson die?', 'He pulled down the temple', 'He was killed in battle', 'He was executed', 'He died of old age', 0, 'easy', 'Judges', 16, 30, NOW()),
('Who was Ruth''s mother-in-law?', 'Naomi', 'Orpah', 'Sarah', 'Rebekah', 0, 'easy', 'Ruth', 1, 4, NOW()),
('Where was Ruth from?', 'Moab', 'Israel', 'Egypt', 'Babylon', 0, 'easy', 'Ruth', 1, 4, NOW()),
('Who did Ruth marry?', 'Boaz', 'Mahlon', 'Chilion', 'Elimelek', 0, 'easy', 'Ruth', 4, 13, NOW()),
('Who was Ruth''s great-grandson?', 'David', 'Solomon', 'Saul', 'Samuel', 0, 'easy', 'Ruth', 4, 22, NOW()),
('Who was Samuel''s mother?', 'Hannah', 'Peninnah', 'Abigail', 'Michal', 0, 'easy', '1 Samuel', 1, 2, NOW()),
('What did Hannah promise God?', 'To give her son to God', 'To build a temple', 'To serve God', 'To pray every day', 0, 'easy', '1 Samuel', 1, 11, NOW()),
('Where did Samuel grow up?', 'In the temple', 'At home', 'In the desert', 'In a palace', 0, 'easy', '1 Samuel', 2, 11, NOW()),
('How many times did God call Samuel?', '1 time', '2 times', '3 times', '4 times', 2, 'easy', '1 Samuel', 3, 8, NOW()),
('What did Samuel become?', 'A judge and prophet', 'A king', 'A priest', 'A warrior', 0, 'easy', '1 Samuel', 3, 20, NOW()),
('Who was the first king of Israel?', 'Saul', 'David', 'Solomon', 'Samuel', 0, 'easy', '1 Samuel', 10, 1, NOW()),
('How was Saul chosen?', 'By lot', 'By vote', 'By God', 'By Samuel', 2, 'easy', '1 Samuel', 10, 1, NOW()),
('What was Saul''s job before he became king?', 'A farmer', 'A shepherd', 'A warrior', 'A priest', 0, 'easy', '1 Samuel', 11, 5, NOW()),
('Who anointed David as king?', 'Samuel', 'Saul', 'Nathan', 'Gad', 0, 'easy', '1 Samuel', 16, 13, NOW()),
('What was David''s job before he became king?', 'A farmer', 'A shepherd', 'A warrior', 'A priest', 1, 'easy', '1 Samuel', 16, 11, NOW()),
('How many brothers did David have?', '6', '7', '8', '9', 1, 'easy', '1 Samuel', 16, 10, NOW()),
('What did David play?', 'A harp', 'A flute', 'A trumpet', 'A drum', 0, 'easy', '1 Samuel', 16, 23, NOW()),
('What did David do for Saul?', 'Played music', 'Fought battles', 'Both', 'Neither', 2, 'easy', '1 Samuel', 18, 5, NOW()),
('How tall was Goliath?', 'About 6 feet', 'About 7 feet', 'About 9 feet', 'About 10 feet', 2, 'easy', '1 Samuel', 17, 4, NOW()),
('What did David use to kill Goliath?', 'A sword', 'A spear', 'A sling and a stone', 'A bow and arrow', 2, 'easy', '1 Samuel', 17, 50, NOW()),
('How many stones did David take?', '1 stone', '3 stones', '5 stones', '7 stones', 2, 'easy', '1 Samuel', 17, 40, NOW()),
('Who was David''s best friend?', 'Jonathan', 'Saul', 'Samuel', 'Nathan', 0, 'easy', '1 Samuel', 18, 1, NOW()),
('How many times did David spare Saul''s life?', '1 time', '2 times', '3 times', '4 times', 1, 'easy', '1 Samuel', 24, 4, NOW()),
('What was the name of the cave where David hid?', 'Cave of Adullam', 'Cave of En Gedi', 'Cave of Machpelah', 'Cave of Horeb', 1, 'easy', '1 Samuel', 24, 3, NOW()),
('How many years did David rule?', '30 years', '40 years', '50 years', '60 years', 1, 'easy', '2 Samuel', 5, 4, NOW()),
('What was the name of David''s son who became king?', 'Absalom', 'Adonijah', 'Solomon', 'Amnon', 2, 'easy', '1 Kings', 1, 30, NOW()),
('How many years did Solomon rule?', '30 years', '40 years', '50 years', '60 years', 1, 'easy', '1 Kings', 11, 42, NOW()),
('What did Solomon ask God for?', 'Wealth', 'Wisdom', 'Power', 'Long life', 1, 'easy', '1 Kings', 3, 9, NOW()),
('How many years did it take to build the temple?', '5 years', '7 years', '10 years', '12 years', 1, 'easy', '1 Kings', 6, 38, NOW()),
('What queen visited Solomon?', 'Queen of Sheba', 'Queen of Egypt', 'Queen of Persia', 'Queen of Babylon', 0, 'easy', '1 Kings', 10, 1, NOW()),
('How many proverbs did Solomon write?', '1000', '2000', '3000', '4000', 2, 'easy', '1 Kings', 4, 32, NOW()),
('What happened to the kingdom after Solomon?', 'It split in two', 'It was destroyed', 'It grew larger', 'Nothing', 0, 'easy', '1 Kings', 12, 19, NOW()),
('What were the two kingdoms called?', 'Israel and Judah', 'North and South', 'Samaria and Jerusalem', 'Ephraim and Benjamin', 0, 'easy', '1 Kings', 12, 19, NOW()),
('Who was the prophet who was taken to heaven?', 'Elijah', 'Elisha', 'Isaiah', 'Jeremiah', 0, 'easy', '2 Kings', 2, 11, NOW()),
('What did Elisha ask for?', 'A double portion of Elijah''s spirit', 'Wealth', 'Power', 'Long life', 0, 'easy', '2 Kings', 2, 9, NOW()),
('How many miracles did Elisha perform?', 'About 10', 'About 15', 'About 20', 'More than Elijah', 3, 'easy', '2 Kings', NULL, NULL, NOW()),
('Who did Elisha heal?', 'Naaman', 'The Shunammite woman''s son', 'Both', 'Neither', 2, 'easy', '2 Kings', 5, 14, NOW()),
('What river did Naaman wash in?', 'Jordan River', 'Nile River', 'Euphrates River', 'Tigris River', 0, 'easy', '2 Kings', 5, 10, NOW()),
('How many times did Elisha tell Naaman to wash?', '5 times', '6 times', '7 times', '8 times', 2, 'easy', '2 Kings', 5, 10, NOW()),
('Who was thrown into a lions'' den?', 'Daniel', 'Shadrach', 'Meshach', 'Abednego', 0, 'easy', 'Daniel', 6, 16, NOW()),
('How many days was Daniel in the lions'' den?', 'One night', 'Three days', 'Seven days', 'Forty days', 0, 'easy', 'Daniel', 6, 19, NOW()),
('Who was thrown into a fiery furnace?', 'Daniel', 'Shadrach, Meshach, and Abednego', 'Moses', 'Elijah', 1, 'easy', 'Daniel', 3, 23, NOW()),
('What happened in the fiery furnace?', 'They were burned', 'They were saved by an angel', 'They escaped', 'They died', 1, 'easy', 'Daniel', 3, 25, NOW()),
('What did Daniel do three times a day?', 'Ate', 'Prayed', 'Worked', 'Slept', 1, 'easy', 'Daniel', 6, 10, NOW()),
('What did Daniel interpret?', 'Dreams', 'Visions', 'Both', 'Neither', 2, 'easy', 'Daniel', 2, 19, NOW()),
('What was the name of the king who had a dream?', 'Nebuchadnezzar', 'Belshazzar', 'Darius', 'Cyrus', 0, 'easy', 'Daniel', 2, 1, NOW()),
('What was the name of the king who saw writing on the wall?', 'Nebuchadnezzar', 'Belshazzar', 'Darius', 'Cyrus', 1, 'easy', 'Daniel', 5, 1, NOW()),
('What did the writing say?', 'MENE, MENE, TEKEL, PARSIN', 'You are weighed', 'Your kingdom is divided', 'All of the above', 3, 'easy', 'Daniel', 5, 25, NOW()),
('What happened to Belshazzar?', 'He was killed', 'He was captured', 'He escaped', 'He repented', 0, 'easy', 'Daniel', 5, 30, NOW()),
('Who was the prophet who was swallowed by a fish?', 'Jonah', 'Daniel', 'Isaiah', 'Jeremiah', 0, 'easy', 'Jonah', 1, 17, NOW()),
('How many days was Jonah in the fish?', '1 day', '2 days', '3 days', '4 days', 2, 'easy', 'Jonah', 1, 17, NOW()),
('What did God tell Jonah to do?', 'Go to Nineveh', 'Preach to Nineveh', 'Tell them to repent', 'All of the above', 3, 'easy', 'Jonah', 1, 2, NOW()),
('What did the people of Nineveh do?', 'They repented', 'They ignored Jonah', 'They killed Jonah', 'They ran away', 0, 'easy', 'Jonah', 3, 5, NOW()),
('What made Jonah angry?', 'God forgave Nineveh', 'The people didn''t listen', 'He was tired', 'He was hungry', 0, 'easy', 'Jonah', 4, 1, NOW()),
('What did God provide for Jonah?', 'A plant for shade', 'Food', 'Water', 'All of the above', 3, 'easy', 'Jonah', 4, 6, NOW()),
('Who was the prophet who predicted Jesus'' birth?', 'Isaiah', 'Jeremiah', 'Micah', 'All of the above', 3, 'easy', 'Isaiah', 7, 14, NOW()),
('What did Isaiah predict about Jesus?', 'He would be born in Bethlehem', 'He would be called Immanuel', 'He would suffer', 'All of the above', 3, 'easy', 'Isaiah', 7, 14, NOW()),
('What did Micah predict?', 'Jesus would be born in Bethlehem', 'Jesus would be a king', 'Jesus would save people', 'All of the above', 3, 'easy', 'Micah', 5, 2, NOW()),
('Who was the prophet who was thrown into a cistern?', 'Jeremiah', 'Isaiah', 'Ezekiel', 'Daniel', 0, 'easy', 'Jeremiah', 38, 6, NOW()),
('How many years did Jeremiah prophesy?', 'About 20 years', 'About 30 years', 'About 40 years', 'About 50 years', 2, 'easy', 'Jeremiah', 1, 2, NOW()),
('What was Jeremiah known as?', 'The weeping prophet', 'The angry prophet', 'The happy prophet', 'The quiet prophet', 0, 'easy', 'Jeremiah', NULL, NULL, NOW()),
('Who was the prophet who had many visions?', 'Ezekiel', 'Isaiah', 'Jeremiah', 'Daniel', 0, 'easy', 'Ezekiel', 1, 1, NOW()),
('What was Ezekiel known for?', 'His visions', 'His parables', 'His poetry', 'All of the above', 3, 'easy', 'Ezekiel', NULL, NULL, NOW()),
('Who was the Persian king who let the Jews return?', 'Cyrus', 'Darius', 'Artaxerxes', 'Xerxes', 0, 'easy', 'Ezra', 1, 1, NOW()),
('Who led the Jews back to Jerusalem?', 'Zerubbabel', 'Ezra', 'Nehemiah', 'All of the above', 3, 'easy', 'Ezra', 2, 2, NOW()),
('What did Nehemiah rebuild?', 'The temple', 'The wall of Jerusalem', 'The palace', 'The city', 1, 'easy', 'Nehemiah', 2, 17, NOW()),
('How many days did it take to rebuild the wall?', '42 days', '52 days', '62 days', '72 days', 1, 'easy', 'Nehemiah', 6, 15, NOW()),
('Who was the queen who saved her people?', 'Vashti', 'Esther', 'Zeresh', 'Hegai', 1, 'easy', 'Esther', 2, 17, NOW()),
('What was Esther''s other name?', 'Hadassah', 'Vashti', 'Zeresh', 'Hegai', 0, 'easy', 'Esther', 2, 7, NOW()),
('Who was Esther''s cousin?', 'Mordecai', 'Haman', 'Xerxes', 'Bigthana', 0, 'easy', 'Esther', 2, 7, NOW()),
('What did Mordecai refuse to do?', 'Bow to Haman', 'Eat with Haman', 'Talk to Haman', 'Work for Haman', 0, 'easy', 'Esther', 3, 2, NOW()),
('What did Haman plan to do?', 'Kill all the Jews', 'Kill Mordecai', 'Kill Esther', 'All of the above', 3, 'easy', 'Esther', 3, 6, NOW()),
('What did Esther do?', 'Asked the king to save her people', 'Risked her life', 'Had a banquet', 'All of the above', 3, 'easy', 'Esther', 4, 16, NOW()),
('What happened to Haman?', 'He was hanged', 'He was killed', 'He was banished', 'He escaped', 0, 'easy', 'Esther', 7, 10, NOW()),
('What happened to Job?', 'He lost everything', 'He got sick', 'He was tested', 'All of the above', 3, 'easy', 'Job', 1, 13, NOW()),
('How many friends came to comfort Job?', '2', '3', '4', '5', 1, 'easy', 'Job', 2, 11, NOW()),
('What were the names of Job''s friends?', 'Eliphaz, Bildad, and Zophar', 'Just Eliphaz', 'Just Bildad', 'Just Zophar', 0, 'easy', 'Job', 2, 11, NOW()),
('What did Job do?', 'Cursed God', 'Blessed God', 'Got angry', 'Gave up', 1, 'easy', 'Job', 1, 21, NOW()),
('What happened to Job in the end?', 'He was restored', 'He got everything back', 'He was blessed', 'All of the above', 3, 'easy', 'Job', 42, 10, NOW()),
('How many books are in the Old Testament?', '37', '38', '39', '40', 2, 'easy', NULL, NULL, NULL, NOW()),
('How many books are in the New Testament?', '25', '26', '27', '28', 2, 'easy', NULL, NULL, NULL, NOW()),
('How many books are in the whole Bible?', '64', '65', '66', '67', 2, 'easy', NULL, NULL, NULL, NOW()),
('What are the first five books called?', 'The Law', 'The Pentateuch', 'The Torah', 'All of the above', 3, 'easy', NULL, NULL, NULL, NOW()),
('Who wrote the first five books?', 'Moses', 'Aaron', 'Joshua', 'Samuel', 0, 'easy', NULL, NULL, NULL, NOW()),
('What are the four Gospels?', 'Matthew, Mark, Luke, John', 'Matthew, Mark, Paul, John', 'Luke, John, Acts, Romans', 'Matthew, Luke, John, Revelation', 0, 'easy', NULL, NULL, NULL, NOW()),
('What does "Gospel" mean?', 'Story', 'Good news', 'History', 'Letter', 1, 'easy', NULL, NULL, NULL, NOW()),
('Who wrote the Book of Acts?', 'Luke', 'Paul', 'Peter', 'John', 0, 'easy', 'Acts', 1, 1, NOW()),
('What is the Book of Acts about?', 'The early church', 'The apostles', 'The spread of the gospel', 'All of the above', 3, 'easy', 'Acts', NULL, NULL, NOW()),
('What happened on the Day of Pentecost?', 'The Holy Spirit came', 'Tongues of fire appeared', 'People spoke in tongues', 'All of the above', 3, 'easy', 'Acts', 2, 1, NOW()),
('How many people were added on Pentecost?', 'About 2000', 'About 3000', 'About 4000', 'About 5000', 1, 'easy', 'Acts', 2, 41, NOW()),
('Who was the first person to preach after Pentecost?', 'Peter', 'Paul', 'John', 'James', 0, 'easy', 'Acts', 2, 14, NOW()),
('What happened to Ananias and Sapphira?', 'They were blessed', 'They died for lying', 'They were healed', 'They became leaders', 1, 'easy', 'Acts', 5, 5, NOW()),
('Who was the first Christian martyr?', 'Peter', 'Paul', 'Stephen', 'James', 2, 'easy', 'Acts', 7, 59, NOW()),
('Who was converted on the road to Damascus?', 'Peter', 'Paul', 'Stephen', 'Barnabas', 1, 'easy', 'Acts', 9, 3, NOW()),
('What was Paul''s name before?', 'Peter', 'Saul', 'Simon', 'John', 1, 'easy', 'Acts', 9, 1, NOW()),
('Who baptized Paul?', 'Peter', 'Ananias', 'Barnabas', 'John', 1, 'easy', 'Acts', 9, 18, NOW()),
('How many missionary journeys did Paul take?', '1', '2', '3', '4', 2, 'easy', NULL, NULL, NULL, NOW()),
('Who was Paul''s first companion?', 'Barnabas', 'Silas', 'Timothy', 'Luke', 0, 'easy', 'Acts', 13, 2, NOW()),
('What was Paul''s job?', 'Fisherman', 'Tentmaker', 'Carpenter', 'Farmer', 1, 'easy', 'Acts', 18, 3, NOW()),
('How many books did Paul write?', '10', '11', '12', '13', 3, 'easy', NULL, NULL, NULL, NOW()),
('What are Paul''s letters called?', 'Epistles', 'Gospels', 'Prophecies', 'Poems', 0, 'easy', NULL, NULL, NULL, NOW()),
('What is the longest letter?', 'Romans', '1 Corinthians', '2 Corinthians', 'Ephesians', 0, 'easy', 'Romans', NULL, NULL, NOW()),
('What is 1 Corinthians 13 about?', 'Love', 'Faith', 'Hope', 'Joy', 0, 'easy', '1 Corinthians', 13, 1, NOW()),
('What is the fruit of the Spirit?', 'Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control', 'Just love', 'Just joy', 'Just peace', 0, 'easy', 'Galatians', 5, 22, NOW()),
('What is the armor of God?', 'Belt of truth, breastplate of righteousness, shoes of peace, shield of faith, helmet of salvation, sword of the Spirit', 'Just a shield', 'Just a sword', 'Just a helmet', 0, 'easy', 'Ephesians', 6, 13, NOW()),
('What is Philippians about?', 'Joy', 'Love', 'Peace', 'Hope', 0, 'easy', 'Philippians', 4, 4, NOW()),
('Who wrote Hebrews?', 'Unknown (possibly Paul)', 'Peter', 'John', 'James', 0, 'easy', 'Hebrews', 1, 1, NOW()),
('Who wrote James?', 'James the brother of Jesus', 'James the son of Zebedee', 'James the son of Alphaeus', 'All of the above', 0, 'easy', 'James', 1, 1, NOW()),
('What is James about?', 'Faith and works', 'Love', 'Hope', 'Joy', 0, 'easy', 'James', 2, 14, NOW()),
('Who wrote 1 and 2 Peter?', 'Peter', 'Paul', 'John', 'James', 0, 'easy', '1 Peter', 1, 1, NOW()),
('What is 1 Peter about?', 'Suffering and hope', 'Love', 'Faith', 'Joy', 0, 'easy', '1 Peter', 1, 3, NOW()),
('Who wrote 1, 2, and 3 John?', 'John the apostle', 'John the Baptist', 'John Mark', 'Another John', 0, 'easy', '1 John', 1, 1, NOW()),
('What is 1 John about?', 'Love', 'Light', 'Life', 'All of the above', 3, 'easy', '1 John', 1, 5, NOW()),
('Who wrote Jude?', 'Jude the brother of Jesus', 'Judas Iscariot', 'Jude the apostle', 'Another Jude', 0, 'easy', 'Jude', 1, 1, NOW()),
('Who wrote Revelation?', 'John the apostle', 'John the Baptist', 'John Mark', 'Another John', 0, 'easy', 'Revelation', 1, 1, NOW()),
('What is Revelation about?', 'The end times', 'The future', 'Jesus'' return', 'All of the above', 3, 'easy', 'Revelation', NULL, NULL, NOW()),
('What are the seven churches?', 'Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia, Laodicea', 'Just the first church', 'All churches', 'None of the above', 0, 'easy', 'Revelation', 2, 1, NOW()),
('What is the New Jerusalem?', 'A city', 'Heaven', 'The new earth', 'All of the above', 3, 'easy', 'Revelation', 21, 2, NOW()),
('What is the tree of life?', 'A tree in the garden', 'A tree in heaven', 'A symbol of eternal life', 'All of the above', 3, 'easy', 'Revelation', 22, 2, NOW());

-- ========== ADDITIONAL MODERATE QUESTIONS (101-150) ==========
-- Add 50 more moderate questions below

-- Sample Moderate Questions (Add 50 more following this format):

INSERT INTO bible_trivia_questions (question, option_1, option_2, option_3, option_4, correct_answer_index, difficulty, bible_book, bible_chapter, bible_verse, created_at) VALUES
('What was the name of the river where Naaman was told to wash?', 'Jordan River', 'Nile River', 'Euphrates River', 'Tigris River', 0, 'moderate', '2 Kings', 5, 10, NOW()),
('Who was the prophet who anointed Jehu as king?', 'Elijah', 'Elisha', 'Isaiah', 'Jeremiah', 1, 'moderate', '2 Kings', 9, 1, NOW()),
('What was the name of the valley where David fought Goliath?', 'Valley of Elah', 'Valley of Jezreel', 'Kidron Valley', 'Valley of Aijalon', 0, 'moderate', '1 Samuel', 17, 2, NOW()),
('How many years did the Israelites wander in the desert?', '30 years', '40 years', '50 years', '60 years', 1, 'moderate', 'Numbers', 14, 33, NOW()),
('What was the name of the mountain where Moses received the Ten Commandments?', 'Mount Sinai', 'Mount Horeb', 'Mount Zion', 'Mount of Olives', 0, 'moderate', 'Exodus', 19, 20, NOW()),
('Who was the first high priest of Israel?', 'Aaron', 'Moses', 'Eleazar', 'Ithamar', 0, 'moderate', 'Exodus', 28, 1, NOW()),
('What was the name of the tabernacle''s most holy place?', 'Holy of Holies', 'Most Holy Place', 'Sanctuary', 'All of the above', 3, 'moderate', 'Exodus', 26, 33, NOW()),
('How many tribes of Israel were there?', '10', '11', '12', '13', 2, 'moderate', 'Genesis', 49, 28, NOW()),
('What was the name of Jacob''s favorite wife?', 'Leah', 'Rachel', 'Bilhah', 'Zilpah', 1, 'moderate', 'Genesis', 29, 18, NOW()),
('How many sons did Jacob have?', '10', '11', '12', '13', 2, 'moderate', 'Genesis', 35, 22, NOW()),
('What was the name of the well where Jesus met the Samaritan woman?', 'Jacob''s Well', 'Abraham''s Well', 'Isaac''s Well', 'Moses'' Well', 0, 'moderate', 'John', 4, 6, NOW()),
('What was the name of the pool where Jesus healed a man?', 'Pool of Bethesda', 'Pool of Siloam', 'Pool of Gihon', 'Pool of Hezekiah', 0, 'moderate', 'John', 5, 2, NOW()),
('How many times did Jesus appear to his disciples after the resurrection?', '5 times', 'More than 10 times', 'Exactly 10 times', 'Less than 5 times', 1, 'moderate', NULL, NULL, NULL, NOW()),
('What was the name of the place where Jesus was crucified?', 'Golgotha', 'Calvary', 'The Place of the Skull', 'All of the above', 3, 'moderate', 'Matthew', 27, 33, NOW()),
('How many books are in the Old Testament?', '37', '38', '39', '40', 2, 'moderate', NULL, NULL, NULL, NOW()),
('What are the first five books of the Bible called?', 'The Law', 'The Pentateuch', 'The Torah', 'All of the above', 3, 'moderate', NULL, NULL, NULL, NOW()),
('Who wrote the first five books of the Bible?', 'Moses', 'Aaron', 'Joshua', 'Samuel', 0, 'moderate', NULL, NULL, NULL, NOW()),
('What was the name of the sea that the Israelites crossed?', 'Red Sea', 'Dead Sea', 'Sea of Galilee', 'Mediterranean Sea', 0, 'moderate', 'Exodus', 14, 21, NOW()),
('How many plagues did God send to Egypt?', '7', '10', '12', '15', 1, 'moderate', 'Exodus', 7, 14, NOW()),
('What was the last plague?', 'Death of the firstborn', 'Locusts', 'Darkness', 'Hail', 0, 'moderate', 'Exodus', 12, 29, NOW()),
('What was the name of the food God provided in the desert?', 'Bread', 'Manna', 'Quail', 'Both manna and quail', 3, 'moderate', 'Exodus', 16, 13, NOW()),
('How many spies did Moses send to explore Canaan?', '10', '12', '14', '15', 1, 'moderate', 'Numbers', 13, 2, NOW()),
('What were the names of the two spies who gave a good report?', 'Joshua and Caleb', 'Joshua and Eleazar', 'Caleb and Phinehas', 'Joshua and Phinehas', 0, 'moderate', 'Numbers', 14, 6, NOW()),
('How many years did it take to build Solomon''s temple?', '5 years', '7 years', '10 years', '12 years', 1, 'moderate', '1 Kings', 6, 38, NOW()),
('What was the name of the queen who visited Solomon?', 'Queen of Sheba', 'Queen of Egypt', 'Queen of Persia', 'Queen of Babylon', 0, 'moderate', '1 Kings', 10, 1, NOW()),
('How many proverbs did Solomon write?', '1000', '2000', '3000', '4000', 2, 'moderate', '1 Kings', 4, 32, NOW()),
('What was the name of the prophet who confronted David about Bathsheba?', 'Nathan', 'Gad', 'Samuel', 'Ahijah', 0, 'moderate', '2 Samuel', 12, 1, NOW()),
('How many psalms did David write?', 'About 50', 'About 73', 'About 100', 'About 150', 1, 'moderate', 'Psalms', NULL, NULL, NOW()),
('What was the name of David''s son who rebelled against him?', 'Absalom', 'Adonijah', 'Amnon', 'Solomon', 0, 'moderate', '2 Samuel', 15, 1, NOW()),
('How many years did David rule as king?', '30 years', '40 years', '50 years', '60 years', 1, 'moderate', '2 Samuel', 5, 4, NOW()),
('What was the name of the prophet who anointed David?', 'Samuel', 'Nathan', 'Gad', 'Ahijah', 0, 'moderate', '1 Samuel', 16, 13, NOW()),
('How many times did Goliath challenge the Israelites?', '30 days', '40 days', '50 days', '60 days', 1, 'moderate', '1 Samuel', 17, 16, NOW()),
('What was the name of Saul''s son who was David''s friend?', 'Jonathan', 'Ishbosheth', 'Abner', 'Mephibosheth', 0, 'moderate', '1 Samuel', 18, 1, NOW()),
('How many times did David spare Saul''s life?', '1 time', '2 times', '3 times', '4 times', 1, 'moderate', '1 Samuel', 24, 4, NOW()),
('What was the name of the cave where David hid from Saul?', 'Cave of Adullam', 'Cave of En Gedi', 'Cave of Machpelah', 'Cave of Horeb', 1, 'moderate', '1 Samuel', 24, 3, NOW()),
('How many years did the judges rule Israel?', 'About 300 years', 'About 400 years', 'About 500 years', 'About 600 years', 0, 'moderate', 'Judges', NULL, NULL, NOW()),
('What was the name of the judge who was left-handed?', 'Ehud', 'Othniel', 'Shamgar', 'Deborah', 0, 'moderate', 'Judges', 3, 15, NOW()),
('How many men did Gideon start with?', '1000', '2000', '3000', '32000', 3, 'moderate', 'Judges', 7, 3, NOW()),
('How many men did Gideon end up with?', '100', '200', '300', '400', 2, 'moderate', 'Judges', 7, 7, NOW()),
('What was the name of Samson''s first wife?', 'Delilah', 'A Philistine woman from Timnah', 'A woman from Gaza', 'A woman from Ashkelon', 1, 'moderate', 'Judges', 14, 1, NOW()),
('How many Philistines did Samson kill with a jawbone?', '500', '1000', '1500', '2000', 1, 'moderate', 'Judges', 15, 15, NOW()),
('What was the name of Ruth''s second husband?', 'Boaz', 'Mahlon', 'Chilion', 'Elimelek', 0, 'moderate', 'Ruth', 4, 13, NOW()),
('Who was the great-grandmother of David?', 'Ruth', 'Naomi', 'Orpah', 'Tamar', 0, 'moderate', 'Ruth', 4, 17, NOW()),
('How many years did Samuel serve as judge?', 'About 20 years', 'About 30 years', 'About 40 years', 'About 50 years', 2, 'moderate', '1 Samuel', 7, 15, NOW()),
('What was the name of Samuel''s mother?', 'Hannah', 'Peninnah', 'Abigail', 'Michal', 0, 'moderate', '1 Samuel', 1, 2, NOW()),
('How many times did God call Samuel?', '1 time', '2 times', '3 times', '4 times', 2, 'moderate', '1 Samuel', 3, 8, NOW()),
('What was the name of the Philistine god that the ark was placed before?', 'Baal', 'Dagon', 'Ashtoreth', 'Chemosh', 1, 'moderate', '1 Samuel', 5, 2, NOW()),
('How many months was the ark in Philistine territory?', '3 months', '6 months', '7 months', '12 months', 2, 'moderate', '1 Samuel', 6, 1, NOW()),
('What was the name of Saul''s father?', 'Kish', 'Ner', 'Abiel', 'Jeiel', 0, 'moderate', '1 Samuel', 9, 1, NOW()),
('How tall was Goliath?', 'About 6 feet', 'About 7 feet', 'About 9 feet', 'About 10 feet', 2, 'moderate', '1 Samuel', 17, 4, NOW()),
('What was the weight of Goliath''s spear?', 'About 10 pounds', 'About 15 pounds', 'About 20 pounds', 'About 25 pounds', 1, 'moderate', '1 Samuel', 17, 7, NOW()),
('How many stones did David take to fight Goliath?', '1 stone', '3 stones', '5 stones', '7 stones', 2, 'moderate', '1 Samuel', 17, 40, NOW()),
('What was the name of the prophet who anointed Jehu?', 'Elijah', 'Elisha', 'Isaiah', 'Jeremiah', 1, 'moderate', '2 Kings', 9, 1, NOW()),
('How many times did Elisha tell Naaman to wash?', '5 times', '6 times', '7 times', '8 times', 2, 'moderate', '2 Kings', 5, 10, NOW()),
('What was the name of the Shunammite woman who showed Elisha hospitality?', 'Not named', 'Abigail', 'Hannah', 'Ruth', 0, 'moderate', '2 Kings', 4, 8, NOW()),
('How many years did the Shunammite woman''s son live before he died?', '5 years', '7 years', '10 years', '12 years', 1, 'moderate', '2 Kings', 4, 18, NOW()),
('What was the name of the king who found the Book of the Law?', 'Hezekiah', 'Josiah', 'Jehoiakim', 'Zedekiah', 1, 'moderate', '2 Kings', 22, 8, NOW()),
('How old was Josiah when he became king?', '6 years old', '8 years old', '10 years old', '12 years old', 1, 'moderate', '2 Kings', 22, 1, NOW()),
('What was the name of the prophet who was thrown into a cistern?', 'Jeremiah', 'Isaiah', 'Ezekiel', 'Daniel', 0, 'moderate', 'Jeremiah', 38, 6, NOW()),
('How many years did Jeremiah prophesy?', 'About 20 years', 'About 30 years', 'About 40 years', 'About 50 years', 2, 'moderate', 'Jeremiah', 1, 2, NOW()),
('What was the name of the king who had a dream that Daniel interpreted?', 'Nebuchadnezzar', 'Belshazzar', 'Darius', 'Cyrus', 0, 'moderate', 'Daniel', 2, 1, NOW()),
('How many years was Daniel in Babylon?', 'About 50 years', 'About 60 years', 'About 70 years', 'About 80 years', 2, 'moderate', 'Daniel', 1, 21, NOW()),
('What was the name of the king who saw the writing on the wall?', 'Nebuchadnezzar', 'Belshazzar', 'Darius', 'Cyrus', 1, 'moderate', 'Daniel', 5, 1, NOW()),
('How many chapters are in the Book of Daniel?', '10', '11', '12', '13', 2, 'moderate', 'Daniel', NULL, NULL, NOW()),
('What was the name of the Persian king who allowed the Jews to return?', 'Cyrus', 'Darius', 'Artaxerxes', 'Xerxes', 0, 'moderate', 'Ezra', 1, 1, NOW()),
('How many times did Nehemiah pray before asking the king?', '1 day', 'Several days', 'Several months', 'Several years', 2, 'moderate', 'Nehemiah', 1, 4, NOW()),
('How many days did it take to rebuild the wall of Jerusalem?', '42 days', '52 days', '62 days', '72 days', 1, 'moderate', 'Nehemiah', 6, 15, NOW()),
('What was the name of the queen who saved her people?', 'Vashti', 'Esther', 'Zeresh', 'Hegai', 1, 'moderate', 'Esther', 2, 17, NOW()),
('How many times did Mordecai refuse to bow to Haman?', '1 time', 'Many times', 'Every day', 'Never', 2, 'moderate', 'Esther', 3, 2, NOW()),
('What was the name of Job''s wife?', 'Not named', 'Sarah', 'Rebekah', 'Rachel', 0, 'moderate', 'Job', 2, 9, NOW()),
('How many friends came to comfort Job?', '2', '3', '4', '5', 1, 'moderate', 'Job', 2, 11, NOW()),
('What was the name of Job''s first friend?', 'Eliphaz', 'Bildad', 'Zophar', 'Elihu', 0, 'moderate', 'Job', 2, 11, NOW()),
('How many chapters are in the Book of Job?', '40', '41', '42', '43', 2, 'moderate', 'Job', NULL, NULL, NOW()),
('What was the name of the prophet who was taken to heaven?', 'Elijah', 'Elisha', 'Isaiah', 'Jeremiah', 0, 'moderate', '2 Kings', 2, 11, NOW()),
('How many books of prophecy are in the Old Testament?', '15', '16', '17', '18', 2, 'moderate', NULL, NULL, NULL, NOW()),
('What are the Major Prophets?', 'Isaiah, Jeremiah, Lamentations, Ezekiel, Daniel', 'Just Isaiah and Jeremiah', 'All the prophets', 'None of the above', 0, 'moderate', NULL, NULL, NULL, NOW()),
('What are the Minor Prophets?', 'Hosea through Malachi (12 books)', 'Just the short books', 'All except Major Prophets', 'None of the above', 0, 'moderate', NULL, NULL, NULL, NOW()),
('How many chapters are in the Book of Isaiah?', '64', '65', '66', '67', 2, 'moderate', 'Isaiah', NULL, NULL, NOW()),
('What was the name of Isaiah''s son that was a sign?', 'Maher-Shal-Hash-Baz', 'Shear-Jashub', 'Immanuel', 'All of the above', 3, 'moderate', 'Isaiah', 7, 14, NOW()),
('How many chapters are in the Book of Jeremiah?', '50', '51', '52', '53', 2, 'moderate', 'Jeremiah', NULL, NULL, NOW()),
('What was the name of Jeremiah''s scribe?', 'Baruch', 'Ebed-Melech', 'Gedaliah', 'Ishmael', 0, 'moderate', 'Jeremiah', 36, 4, NOW()),
('How many chapters are in the Book of Ezekiel?', '46', '47', '48', '49', 2, 'moderate', 'Ezekiel', NULL, NULL, NOW()),
('What was Ezekiel known for?', 'His visions', 'His parables', 'His poetry', 'All of the above', 3, 'moderate', 'Ezekiel', NULL, NULL, NOW()),
('How many chapters are in the Book of Daniel?', '10', '11', '12', '13', 2, 'moderate', 'Daniel', NULL, NULL, NOW()),
('What was Daniel known for?', 'Interpreting dreams', 'Surviving the lions'' den', 'Praying three times a day', 'All of the above', 3, 'moderate', 'Daniel', NULL, NULL, NOW()),
('How many chapters are in the Book of Hosea?', '13', '14', '15', '16', 1, 'moderate', 'Hosea', NULL, NULL, NOW()),
('What was Hosea told to do?', 'Marry an unfaithful woman', 'Go to Nineveh', 'Preach to Israel', 'Write a book', 0, 'moderate', 'Hosea', 1, 2, NOW()),
('How many chapters are in the Book of Joel?', '2', '3', '4', '5', 1, 'moderate', 'Joel', NULL, NULL, NOW()),
('What was the main theme of Joel?', 'The Day of the Lord', 'Repentance', 'Restoration', 'All of the above', 3, 'moderate', 'Joel', NULL, NULL, NOW()),
('How many chapters are in the Book of Amos?', '8', '9', '10', '11', 1, 'moderate', 'Amos', NULL, NULL, NOW()),
('What was Amos'' job before he became a prophet?', 'Shepherd', 'Farmer', 'Both', 'Neither', 2, 'moderate', 'Amos', 1, 1, NOW()),
('How many chapters are in the Book of Obadiah?', '1', '2', '3', '4', 0, 'moderate', 'Obadiah', NULL, NULL, NOW()),
('What is the shortest book in the Old Testament?', 'Obadiah', 'Haggai', 'Nahum', 'Zephaniah', 0, 'moderate', 'Obadiah', NULL, NULL, NOW()),
('How many chapters are in the Book of Jonah?', '3', '4', '5', '6', 1, 'moderate', 'Jonah', NULL, NULL, NOW()),
('What was Jonah told to do?', 'Go to Nineveh', 'Preach to Nineveh', 'Tell them to repent', 'All of the above', 3, 'moderate', 'Jonah', 1, 2, NOW()),
('How many chapters are in the Book of Micah?', '6', '7', '8', '9', 1, 'moderate', 'Micah', NULL, NULL, NOW()),
('What was Micah known for?', 'Predicting Bethlehem as birthplace of Messiah', 'Calling for justice', 'Speaking against false prophets', 'All of the above', 3, 'moderate', 'Micah', 5, 2, NOW()),
('How many chapters are in the Book of Nahum?', '2', '3', '4', '5', 1, 'moderate', 'Nahum', NULL, NULL, NOW()),
('What was Nahum''s main message?', 'Judgment on Nineveh', 'Hope for Israel', 'Call to repentance', 'All of the above', 0, 'moderate', 'Nahum', 1, 1, NOW()),
('How many chapters are in the Book of Habakkuk?', '2', '3', '4', '5', 1, 'moderate', 'Habakkuk', NULL, NULL, NOW()),
('What was Habakkuk''s main question?', 'Why does God allow evil?', 'When will God act?', 'How long must we wait?', 'All of the above', 3, 'moderate', 'Habakkuk', 1, 2, NOW()),
('How many chapters are in the Book of Zephaniah?', '2', '3', '4', '5', 1, 'moderate', 'Zephaniah', NULL, NULL, NOW()),
('What was Zephaniah''s main message?', 'The Day of the Lord', 'Judgment', 'Hope', 'All of the above', 3, 'moderate', 'Zephaniah', 1, 7, NOW()),
('How many chapters are in the Book of Haggai?', '1', '2', '3', '4', 1, 'moderate', 'Haggai', NULL, NULL, NOW()),
('What was Haggai''s main message?', 'Rebuild the temple', 'Return to God', 'Stop being lazy', 'All of the above', 3, 'moderate', 'Haggai', 1, 4, NOW()),
('How many chapters are in the Book of Zechariah?', '13', '14', '15', '16', 1, 'moderate', 'Zechariah', NULL, NULL, NOW()),
('What was Zechariah known for?', 'His visions', 'Encouraging temple rebuilding', 'Messianic prophecies', 'All of the above', 3, 'moderate', 'Zechariah', NULL, NULL, NOW()),
('How many chapters are in the Book of Malachi?', '3', '4', '5', '6', 1, 'moderate', 'Malachi', NULL, NULL, NOW()),
('What was Malachi''s main message?', 'Return to God', 'Stop robbing God', 'The coming messenger', 'All of the above', 3, 'moderate', 'Malachi', 3, 1, NOW()),
('What is the last book of the Old Testament?', 'Zechariah', 'Malachi', 'Nehemiah', 'Esther', 1, 'moderate', 'Malachi', NULL, NULL, NOW()),
('How many years were between the Old and New Testaments?', 'About 100 years', 'About 200 years', 'About 400 years', 'About 500 years', 2, 'moderate', NULL, NULL, NULL, NOW()),
('What language was the New Testament written in?', 'Hebrew', 'Aramaic', 'Greek', 'Latin', 2, 'moderate', NULL, NULL, NULL, NOW()),
('What language was the Old Testament written in?', 'Hebrew and Aramaic', 'Just Hebrew', 'Just Aramaic', 'Greek', 0, 'moderate', NULL, NULL, NULL, NOW()),
('How many Gospels tell the story of Jesus?', '3', '4', '5', '6', 1, 'moderate', NULL, NULL, NULL, NOW()),
('What are the Synoptic Gospels?', 'Matthew, Mark, and Luke', 'All four Gospels', 'Just Matthew and Mark', 'Just Luke and John', 0, 'moderate', NULL, NULL, NULL, NOW()),
('Why is John different from the other Gospels?', 'It was written later', 'It focuses on different aspects', 'It has different stories', 'All of the above', 3, 'moderate', NULL, NULL, NULL, NOW()),
('How many miracles are recorded in the Gospels?', 'About 30', 'About 35', 'About 40', 'About 50', 1, 'moderate', NULL, NULL, NULL, NOW()),
('How many parables did Jesus tell?', 'About 30', 'About 35', 'About 40', 'About 50', 2, 'moderate', NULL, NULL, NULL, NOW()),
('What was the first miracle Jesus performed?', 'Healing a leper', 'Turning water into wine', 'Healing a paralytic', 'Feeding 5000', 1, 'moderate', 'John', 2, 11, NOW()),
('How many people did Jesus feed with 5 loaves and 2 fish?', '4000', '5000', '6000', '7000', 1, 'moderate', 'Matthew', 14, 21, NOW()),
('How many people did Jesus feed the second time?', '3000', '4000', '5000', '6000', 1, 'moderate', 'Matthew', 15, 38, NOW()),
('Who did Jesus raise from the dead?', 'Lazarus, Jairus'' daughter, and a widow''s son', 'Just Lazarus', 'Just Jairus'' daughter', 'Just a widow''s son', 0, 'moderate', NULL, NULL, NULL, NOW()),
('What was the name of Jairus'' daughter?', 'Not named', 'Mary', 'Martha', 'Lydia', 0, 'moderate', 'Mark', 5, 41, NOW()),
('What was the name of the widow''s son?', 'Not named', 'Lazarus', 'Timothy', 'John', 0, 'moderate', 'Luke', 7, 12, NOW()),
('How many times did Jesus predict his death?', '1', '2', '3', '4', 2, 'moderate', NULL, NULL, NULL, NOW()),
('What did Jesus say would happen to the temple?', 'It would be destroyed', 'Not one stone would be left', 'It would be rebuilt', 'All of the above', 3, 'moderate', 'Matthew', 24, 2, NOW()),
('How many times did Peter deny Jesus?', '1', '2', '3', '4', 2, 'moderate', 'Matthew', 26, 75, NOW()),
('What did the rooster do when Peter denied Jesus?', 'Crowed once', 'Crowed twice', 'Crowed three times', 'Did not crow', 1, 'moderate', 'Mark', 14, 72, NOW()),
('How many pieces of silver did Judas receive?', '20', '30', '40', '50', 1, 'moderate', 'Matthew', 26, 15, NOW()),
('What did Judas do with the money?', 'Kept it', 'Returned it', 'Threw it in the temple', 'Gave it to the poor', 2, 'moderate', 'Matthew', 27, 5, NOW()),
('What was the name of the place where Jesus was crucified?', 'Golgotha', 'Calvary', 'The Place of the Skull', 'All of the above', 3, 'moderate', 'Matthew', 27, 33, NOW()),
('What time was Jesus crucified?', '6 AM', '9 AM', '12 PM', '3 PM', 1, 'moderate', 'Mark', 15, 25, NOW()),
('What time did Jesus die?', '12 PM', '3 PM', '6 PM', '9 PM', 1, 'moderate', 'Mark', 15, 34, NOW()),
('What happened when Jesus died?', 'The temple curtain tore', 'There was an earthquake', 'Tombs opened', 'All of the above', 3, 'moderate', 'Matthew', 27, 51, NOW()),
('Who was the centurion who said "Surely this was the Son of God"?', 'Not named', 'Cornelius', 'Another centurion', 'All of the above', 0, 'moderate', 'Matthew', 27, 54, NOW()),
('Who buried Jesus?', 'Joseph of Arimathea and Nicodemus', 'Just Joseph', 'Just Nicodemus', 'The disciples', 0, 'moderate', 'John', 19, 38, NOW()),
('What day of the week did Jesus rise?', 'Friday', 'Saturday', 'Sunday', 'Monday', 2, 'moderate', 'Matthew', 28, 1, NOW()),
('What time of day did the women go to the tomb?', 'Early morning', 'Midday', 'Evening', 'Night', 0, 'moderate', 'Matthew', 28, 1, NOW()),
('Who was the first to see the risen Jesus?', 'Peter', 'Mary Magdalene', 'The other women', 'The disciples', 1, 'moderate', 'John', 20, 14, NOW()),
('How many times did Jesus appear after the resurrection?', '5', '10', 'More than 10', 'Less than 5', 2, 'moderate', NULL, NULL, NULL, NOW()),
('Where did Jesus appear to the disciples?', 'In Jerusalem', 'In Galilee', 'On the road to Emmaus', 'All of the above', 3, 'moderate', NULL, NULL, NULL, NOW()),
('How many days after rising did Jesus ascend?', '30', '40', '50', '60', 1, 'moderate', 'Acts', 1, 3, NOW()),
('Where did Jesus ascend from?', 'Mount of Olives', 'Mount Sinai', 'Mount Tabor', 'Mount Zion', 0, 'moderate', 'Acts', 1, 9, NOW()),
('How many people were in the upper room?', 'About 100', 'About 110', 'About 120', 'About 130', 2, 'moderate', 'Acts', 1, 15, NOW()),
('What happened on the Day of Pentecost?', 'The Holy Spirit came', 'Tongues of fire appeared', 'People spoke in tongues', 'All of the above', 3, 'moderate', 'Acts', 2, 1, NOW()),
('How many people were added to the church on Pentecost?', 'About 2000', 'About 3000', 'About 4000', 'About 5000', 1, 'moderate', 'Acts', 2, 41, NOW()),
('Who was the first person to preach after Pentecost?', 'Peter', 'Paul', 'John', 'James', 0, 'moderate', 'Acts', 2, 14, NOW()),
('What happened to Ananias and Sapphira?', 'They were blessed', 'They died for lying', 'They were healed', 'They became leaders', 1, 'moderate', 'Acts', 5, 5, NOW()),
('Who was the first Christian martyr?', 'Peter', 'Paul', 'Stephen', 'James', 2, 'moderate', 'Acts', 7, 59, NOW()),
('Who was converted on the road to Damascus?', 'Peter', 'Paul', 'Stephen', 'Barnabas', 1, 'moderate', 'Acts', 9, 3, NOW()),
('What was Paul''s name before conversion?', 'Peter', 'Saul', 'Simon', 'John', 1, 'moderate', 'Acts', 9, 1, NOW()),
('Who baptized Paul?', 'Peter', 'Ananias', 'Barnabas', 'John', 1, 'moderate', 'Acts', 9, 18, NOW()),
('How many missionary journeys did Paul take?', '1', '2', '3', '4', 2, 'moderate', NULL, NULL, NULL, NOW()),
('Who was Paul''s first missionary companion?', 'Barnabas', 'Silas', 'Timothy', 'Luke', 0, 'moderate', 'Acts', 13, 2, NOW()),
('What was Paul''s job?', 'Fisherman', 'Tentmaker', 'Carpenter', 'Farmer', 1, 'moderate', 'Acts', 18, 3, NOW()),
('How many books did Paul write?', '10', '11', '12', '13', 3, 'moderate', NULL, NULL, NULL, NOW()),
('What are Paul''s letters called?', 'Epistles', 'Gospels', 'Prophecies', 'Poems', 0, 'moderate', NULL, NULL, NULL, NOW()),
('What is the longest of Paul''s letters?', 'Romans', '1 Corinthians', '2 Corinthians', 'Ephesians', 0, 'moderate', 'Romans', NULL, NULL, NOW()),
('What is the theme of 1 Corinthians 13?', 'Love', 'Faith', 'Hope', 'Joy', 0, 'moderate', '1 Corinthians', 13, 1, NOW()),
('What is the fruit of the Spirit?', 'Love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, self-control', 'Just love', 'Just joy', 'Just peace', 0, 'moderate', 'Galatians', 5, 22, NOW()),
('What is the armor of God?', 'Belt of truth, breastplate of righteousness, shoes of peace, shield of faith, helmet of salvation, sword of the Spirit', 'Just a shield', 'Just a sword', 'Just a helmet', 0, 'moderate', 'Ephesians', 6, 13, NOW()),
('What is the theme of Philippians?', 'Joy', 'Love', 'Peace', 'Hope', 0, 'moderate', 'Philippians', 4, 4, NOW()),
('Who wrote the Book of Hebrews?', 'Unknown (possibly Paul)', 'Peter', 'John', 'James', 0, 'moderate', 'Hebrews', 1, 1, NOW()),
('Who wrote the Book of James?', 'James the brother of Jesus', 'James the son of Zebedee', 'James the son of Alphaeus', 'All of the above', 0, 'moderate', 'James', 1, 1, NOW()),
('What is the main theme of James?', 'Faith and works', 'Love', 'Hope', 'Joy', 0, 'moderate', 'James', 2, 14, NOW()),
('Who wrote 1 and 2 Peter?', 'Peter', 'Paul', 'John', 'James', 0, 'moderate', '1 Peter', 1, 1, NOW()),
('What is the main theme of 1 Peter?', 'Suffering and hope', 'Love', 'Faith', 'Joy', 0, 'moderate', '1 Peter', 1, 3, NOW()),
('Who wrote 1, 2, and 3 John?', 'John the apostle', 'John the Baptist', 'John Mark', 'Another John', 0, 'moderate', '1 John', 1, 1, NOW()),
('What is the main theme of 1 John?', 'Love', 'Light', 'Life', 'All of the above', 3, 'moderate', '1 John', 1, 5, NOW()),
('Who wrote the Book of Jude?', 'Jude the brother of Jesus', 'Judas Iscariot', 'Jude the apostle', 'Another Jude', 0, 'moderate', 'Jude', 1, 1, NOW()),
('Who wrote the Book of Revelation?', 'John the apostle', 'John the Baptist', 'John Mark', 'Another John', 0, 'moderate', 'Revelation', 1, 1, NOW()),
('What is the Book of Revelation about?', 'The end times', 'The future', 'Jesus'' return', 'All of the above', 3, 'moderate', 'Revelation', NULL, NULL, NOW()),
('How many chapters are in Revelation?', '20', '21', '22', '23', 2, 'moderate', 'Revelation', NULL, NULL, NOW()),
('What are the seven churches in Revelation?', 'Ephesus, Smyrna, Pergamum, Thyatira, Sardis, Philadelphia, Laodicea', 'Just the first church', 'All churches', 'None of the above', 0, 'moderate', 'Revelation', 2, 1, NOW()),
('What is the New Jerusalem?', 'A city', 'Heaven', 'The new earth', 'All of the above', 3, 'moderate', 'Revelation', 21, 2, NOW()),
('What is the tree of life?', 'A tree in the garden', 'A tree in heaven', 'A symbol of eternal life', 'All of the above', 3, 'moderate', 'Revelation', 22, 2, NOW());

-- Note: This file contains sample questions. You'll need to add more questions to reach:
-- 300 easy questions total (add ~200 more easy questions)
-- 150 moderate questions total (add ~50 more moderate questions)  
-- 100 hard questions total (already have 100, no change needed)

-- After running the initial migration from the JS file, run this file to add the additional questions.

